### ISSUE TITLE
Error when doing command on server 1.21

### ISSUE THREAD

**Issue by Distolfix** [BartuAbiHD/CommandSync-Master#1]
[08:42:22 ERROR]: Thread Thread-16 failed main thread check: Command Dispatched Async: broadcast Hi there people!
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[paper-1.21.jar:1.21-40-b45d9b6]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:987) ~[paper-1.21.jar:1.21-40-b45d9b6]
        at CommandSyncClient.jar/com.fuzzoland.CommandSyncClient.ClientThread.run(ClientThread.java:63) ~[CommandSyncClient.jar:?]
[08:42:22 WARN]: Exception in thread "Thread-16" java.lang.IllegalStateException: Asynchronous Command Dispatched Async: broadcast Hi there people!!
[08:42:22 WARN]:        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15)
[08:42:22 WARN]:        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:987)
[08:42:22 WARN]:        at CommandSyncClient.jar//com.fuzzoland.CommandSyncClient.ClientThread.run(ClientThread.java:63)

**Comment by Distolfix** [comment]
The error you are seeing indicates that a command has been executed asynchronously, whereas it should be executed synchronously on the main thread. In Minecraft servers based on Spigot/Paper, many commands and operations must be executed on the main thread to avoid concurrency issues and ensure the stability of the server.
